[package]
name = "polyhedron-ops"
version = "0.3.0"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2021"
keywords = ["3d", "creative", "geometry", "graphics", "rendering"]
categories = ["graphics", "mathematics", "multimedia", "rendering"]
license = "MIT OR Apache-2.0 OR Zlib"
description = "Conway/Hart Polyhedron Operations"
readme = "README.md"
repository = "https://github.com/virtualritz/polyhedron-ops/"
documentation = "https://docs.rs/polyhedron-ops/"
resolver = "2"

[features]
default = []
# Add support for writing a mesh out as a Wavefront OBJ.
obj = ["tobj"]

[dependencies]
bytemuck = "1.12.3"
itertools = "0.10.5"
num-traits = "0.2.15"
rayon = "1.6.1"
ultraviolet = { version = "0.9.0", features = ["f64"] }
# Optional deps.
# Add support to render polyhedra with NSI.
nsi = { version = "0.6", optional = true, features = ["toolbelt"] }
#nsi = { version = "*", optional = true }
# Add support to convert a Polyhedron into a bevy Mesh.
bevy = { version = "0.9", optional = true, default-features = false }
# The following are dev-dependency used for examples.But if we move that there
# we get hundreds of their depedencies pulled in for a regular build.
# Which is not what we want – the limits of Cargo ...
kiss3d = { version = "0.35.0", optional = true }
tobj = { version = "3.2.3", optional = true }

[dev-dependencies]
dirs = "4.0.0"
slice_as_array = "1.1.0"
smooth-bevy-cameras = "0.6.0"

[dev-dependencies.bevy]
version = "0.9"
features = ["bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_winit", "bevy_gltf", "bevy_render"]
default-features = false

[target.'cfg(target_os = "linux")'.dev-dependencies.bevy]
version = "0.9"
features = ["bevy_asset", "x11", "wayland"]
default-features = false

[profile.release]
lto = "on"
opt-level = 3
codegen-units = 1

[profile.dev]
#split-debuginfo = "unpacked"
opt-level = 3

[[example]]
path = "examples/playground/playground.rs"
name = "playground"
required-features = [ "obj", "kiss3d" ]

[[example]]
path = "examples/bevy/bevy.rs"
name = "bevy"
required-features = [ "bevy" ]

#[[example]]
#path = "examples/bevy-playground/bevy.rs"
#name = "bevy-playground"
#required-features = [ "bevy", "bevy-orbit-controls" ]

[package.metadata.docs.rs]
features = [ "nsi", "obj" ]
