[package]
name = "polyhedron-operators"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
repository = "https://github.com/virtualritz/polyhedron-operators/"

[dependencies]
#itertools = "0.9.0"
cgmath = "0.17.0"
nsi = "0.5.1"
