cargo-features = ["strip"]

[package]
name = "polyhedron-operators"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
repository = "https://github.com/virtualritz/polyhedron-operators/"

[dependencies]
cgmath = "0.17.0"
itertools = "0.9.0"
nalgebra = "0.21.1"
kiss3d = "0.24.1"
rayon = "1.3.1"
dirs = "3.0.1"
nsi = "0.5.3"
slice_as_array = "1.1.0"

[profile.release]
lto = "on"
opt-level = 3
codegen-units = 1
rpath = true
panic = "abort"
strip = "symbols"
