[package]
name = "polyhedron-operators"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
repository = "https://github.com/virtualritz/polyhedron-operators/"

[dependencies]
itertools = "0.9.0"
cgmath = "0.17.0"
nalgebra = "0.21.1"
kiss3d = "0.24.1"
#nsi = { path = "../nsi", version = "0.5.1" }
