cargo-features = ["strip"]

[package]
name = "polyhedron-ops"
version = "0.1.1"
license = "BSD-3-Clause"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"
repository = "https://github.com/virtualritz/polyhedron-ops/"

[dependencies]
clamped = "1.0.0"
ultraviolet = "0.7.5"
itertools = "0.9.0"
rayon = "1.5.0"
nsi = "0.5.4"

[dev-dependencies]
dirs = "3.0.1"
nalgebra = "0.23.0"
kiss3d = "0.27.0"
slice_as_array = "1.1.0"

[profile.release]
lto = "on"
opt-level = 3
codegen-units = 1
rpath = true
panic = "abort"
strip = "symbols"

[profile.dev.package.'*']
opt-level = 3
