[package]
name = "polyhedron-ops"
version = "0.2.4"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2021"
keywords = ["3d", "creative", "geometry", "graphics", "rendering"]
categories = ["graphics", "mathematics", "multimedia", "rendering"]
license = "MIT OR Apache-2.0 OR Zlib"
description = "Conway/Hart Polyhedron Operations"
readme = "README.md"
repository = "https://github.com/virtualritz/polyhedron-ops/"
documentation = "https://docs.rs/polyhedron-ops/"
#resolver = "2"

[features]
default = []
# Add support for writing a mesh out as a Wavefront OBJ.
obj = ["tobj"]

[dependencies]
# Add support to convert a Polyhedron into a bevy Mesh.
bevy = { version = "0.10", optional = true, default-features = false, features = ["bevy_render"] }
bytemuck = "1.13.1"
itertools = "0.10.5"
# The following is a dev-dependency used for examples. But if we move that there
# we get hundreds of their depedencies pulled in for a regular build.
# Which is not what we want – the limits of Cargo ...
kiss3d = { version = "0.35.0", optional = true }
# Add support to render polyhedra with NSI.
nsi = { version = "0.6", optional = true, features = ["toolbelt"] }
num-traits = "0.2.15"
rayon = "1.7.0"
tobj = { version = "3.2.4", optional = true }
ultraviolet = { version = "0.9.1", features = ["f64"] }

[dev-dependencies]
dirs = "5.0.0"
slice_as_array = "1.1.0"
smooth-bevy-cameras = "0.8.0"

[dev-dependencies.bevy]
version = "0.10"
features = ["bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_winit"]
default-features = false

[target.'cfg(target_os = "linux")'.dev-dependencies.bevy]
version = "0.10"
features = ["x11", "wayland"]
default-features = false

[profile.release]
lto = "on"
opt-level = 3
codegen-units = 1

[profile.dev]
#split-debuginfo = "unpacked"
opt-level = 3
    [[example]]
path = "examples/playground/playground.rs"
name = "playground"
required-features = ["obj", "kiss3d"]

[[example]]
path = "examples/bevy/bevy.rs"
name = "bevy"
required-features = ["bevy"]
#[[example]]
#path = "examples/bevy-playground/bevy.rs"
#name = "bevy-playground"
#required-features = [ "bevy", "bevy-orbit-controls" ]

[package.metadata.docs.rs]
features = ["nsi", "obj"]
